using BibliothequeClassesVSC;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;

namespace Stub
{
    public class Stub : IPersistanceManager
    {
        public void SauvegardeDonnées(IEnumerable<ArmePassive> lesArmesPassives,
                                      IEnumerable<ArmeActive> lesArmesActives, 
                                      IEnumerable<Amelioration> lesAmeliorations,
                                      IEnumerable<Personnage> lesPersonnages,
                                      IEnumerable<Ennemie> lesEnnemies,
                                      IEnumerable<Carte> lesCartes)
        {
            Debug.WriteLine("Sauvegarde demandée");
        }

        public (IEnumerable<ArmePassive> lesArmesPassives, 
                IEnumerable<ArmeActive> lesArmesActives, 
                IEnumerable<Amelioration> lesAmeliorations, 
                IEnumerable<Personnage> lesPersonnages,
                IEnumerable<Ennemie> lesEnnemies,
                IEnumerable<Carte> lesCartes) ChargeDonnées()
        {
            HashSet<ArmePassive> lesArmesPassives = new HashSet<ArmePassive>();
            HashSet<ArmeActive> lesArmesActives = new HashSet<ArmeActive>();
            HashSet<Amelioration> lesAmeliorations = new HashSet<Amelioration>();
            HashSet<Personnage> lesPersonnages = new HashSet<Personnage>();
            HashSet<Ennemie> lesEnnemies = new HashSet<Ennemie>();
            HashSet<Carte> lesCartes = new HashSet<Carte>();

            AjoutCollection(lesEnnemies,
                           new Ennemie("Bat", "Bat is an enemy that appears in Mad Forest.", "Sprite-Bat.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxHealth, 1), new Stat(Stat.NomStat.XpGiven, 1), new Stat(Stat.NomStat.Might, 5), new Stat(Stat.NomStat.MoveSpeed, 140), new Stat(Stat.NomStat.KnockbackReceive, 1))),
                           new Ennemie("Red-Eyed Bat", "Red-Eyed Bat is an enemy that appears in Mad Forest and Gallo Tower. It only appears as a normal enemy.", "Sprite-Red_Eyed_Bat.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxHealth, 5), new Stat(Stat.NomStat.XpGiven, 1), new Stat(Stat.NomStat.Might, 5), new Stat(Stat.NomStat.MoveSpeed, 140), new Stat(Stat.NomStat.KnockbackReceive, 1))),
                           new Ennemie("Crimson Bat", "Crimson Bat is an enemy that appears in Gallo Tower. It only appears as a normal enemy.", "Sprite-Crimson_Bat.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxHealth, 11), new Stat(Stat.NomStat.XpGiven, 1), new Stat(Stat.NomStat.Might, 5), new Stat(Stat.NomStat.MoveSpeed, 200), new Stat(Stat.NomStat.KnockbackReceive, 1))),
                           new Ennemie("Skullino", "Skullino is an enemy that appears in Gallo Tower and The Bone Zone. It only appears as a normal enemy.", "Sprite-Skullino.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxHealth, 6), new Stat(Stat.NomStat.XpGiven, 1), new Stat(Stat.NomStat.Might, 5), new Stat(Stat.NomStat.MoveSpeed, 200), new Stat(Stat.NomStat.KnockbackReceive, 1))),
                           new Ennemie("Skulorosso", "Skulorosso is an enemy that appears in Gallo Tower and The Bone Zone. It only appears as a normal enemy.", "Sprite-Skulorosso.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxHealth, 10), new Stat(Stat.NomStat.XpGiven, 1), new Stat(Stat.NomStat.Might, 5), new Stat(Stat.NomStat.MoveSpeed, 200), new Stat(Stat.NomStat.KnockbackReceive, 1))),
                           new Ennemie("Glowing Bat", "Glowing Bat is a boss enemy that appears in Mad Forest, Inlaid Library, Dairy Plant and Gallo Tower. It mostly appears as a boss, but in later waves of Mad Forest it also appears as a normal enemy. When it appears as a boss it has a chance to drop a Treasure Chest.", "Sprite-Glowing_Bat.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxHealth, 50), new Stat(Stat.NomStat.XpGiven, 30), new Stat(Stat.NomStat.Might, 10), new Stat(Stat.NomStat.MoveSpeed, 140), new Stat(Stat.NomStat.KnockbackReceive, 1))),
                           new Ennemie("Silver Bat", "Silver Bat is a boss enemy that appears in Mad Forest and Inlaid Library. It first appears as a boss, but in later stages of Mad Forest it also appears as a normal enemy. When it appears as a boss it has a chance to drop a Treasure Chest.", "Sprite-Silver_Bat.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxHealth, 50), new Stat(Stat.NomStat.XpGiven, 30), new Stat(Stat.NomStat.Might, 10), new Stat(Stat.NomStat.MoveSpeed, 140), new Stat(Stat.NomStat.KnockbackReceive, 1))),
                           new Ennemie("Skelangue", "Skelangue is an enemy that appears in Gallo Tower and The Bone Zone. In Gallo Tower it first appears as a boss and later also as a normal enemy and in The Bone Zone only as a normal enemy. It cannot drop a Treasure Chest.", "Sprite-Skelangue.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxHealth, 15), new Stat(Stat.NomStat.XpGiven, 1), new Stat(Stat.NomStat.Might, 5), new Stat(Stat.NomStat.MoveSpeed, 100), new Stat(Stat.NomStat.KnockbackReceive, 1))),
                           new Ennemie("Skeleton", "Skeleton is an enemy that appears in Mad Forest, Dairy Plant, Gallo Tower and The Bone Zone. In Mad Forest, Gallo Tower and The Bone Zone it only appears as a normal enemy. In Dairy Plant it appears as a normal enemy and as a part of a Swarm map event.", "Sprite-Skeleton.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxHealth, 15), new Stat(Stat.NomStat.XpGiven, 2), new Stat(Stat.NomStat.Might, 10), new Stat(Stat.NomStat.MoveSpeed, 100), new Stat(Stat.NomStat.KnockbackReceive, 1))),
                           new Ennemie("Flower", "Flower is an enemy that appears in Mad Forest. It initially appears as part of Flower Wall event, and later also as a normal enemy.", "Sprite-Flower.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxHealth, 30), new Stat(Stat.NomStat.XpGiven, 2), new Stat(Stat.NomStat.Might, 1), new Stat(Stat.NomStat.MoveSpeed, 20), new Stat(Stat.NomStat.KnockbackReceive, 1))),
                           new Ennemie("Zombie", "Zombie is an enemy that appears in Mad Forest. It only appears as a normal enemy.", "Sprite-Zombie.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxHealth, 10), new Stat(Stat.NomStat.XpGiven, 1), new Stat(Stat.NomStat.Might, 10), new Stat(Stat.NomStat.MoveSpeed, 100), new Stat(Stat.NomStat.KnockbackReceive, 1))),
                           new Ennemie("Gray Mudman", "Gray Mudman is an enemy that appears in Mad Forest. It only appears as a normal enemy.", "Sprite-Gray_Mudman.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxHealth, 70), new Stat(Stat.NomStat.XpGiven, 3), new Stat(Stat.NomStat.Might, 10), new Stat(Stat.NomStat.MoveSpeed, 100), new Stat(Stat.NomStat.KnockbackReceive, 1))),
                           new Ennemie("Green Mudman", "Green Mudman is an enemy that appears in Mad Forest. It only appears as a normal enemy.", "Sprite-Green_Mudman.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxHealth, 15), new Stat(Stat.NomStat.XpGiven, 3), new Stat(Stat.NomStat.Might, 10), new Stat(Stat.NomStat.MoveSpeed, 100), new Stat(Stat.NomStat.KnockbackReceive, 1))),
                           new Ennemie("Werewolf", "Werewolf is an enemy that appears in Mad Forest. It only appears as a normal enemy.", "Sprite-Werewolf.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxHealth, 180), new Stat(Stat.NomStat.XpGiven, 2), new Stat(Stat.NomStat.Might, 14), new Stat(Stat.NomStat.MoveSpeed, 130), new Stat(Stat.NomStat.KnockbackReceive, 1))),
                           new Ennemie("Ghost", "Ghost is an enemy that appears in Mad Forest, Inlaid Library, Gallo Tower and Moongolow. It only appears as a normal enemy.", "Sprite-Ghost.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxHealth, 10), new Stat(Stat.NomStat.XpGiven, 2), new Stat(Stat.NomStat.Might, 5), new Stat(Stat.NomStat.MoveSpeed, 200), new Stat(Stat.NomStat.KnockbackReceive, 0))),
                           new Ennemie("Mud", "Mud is an enemy that appears in Inlaid Library. It only appears as a normal enemy.", "Sprite-Mud.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxHealth, 5), new Stat(Stat.NomStat.XpGiven, 1), new Stat(Stat.NomStat.Might, 5), new Stat(Stat.NomStat.MoveSpeed, 140), new Stat(Stat.NomStat.KnockbackReceive, 1))),
                           new Ennemie("Lion Head", "Lion Head is an enemy that appears in Inlaid Library. It only appears as a normal enemy. Killing 3,000 Lion Heads is the requirement for unlocking Yatta Cavallo.", "Sprite-Lion_Head.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxHealth, 3), new Stat(Stat.NomStat.XpGiven, 2), new Stat(Stat.NomStat.Might, 3), new Stat(Stat.NomStat.MoveSpeed, 200), new Stat(Stat.NomStat.KnockbackReceive, 1))),
                           new Ennemie("Dragon Shrimp", "Dragon Shrimp is an enemy that appears in Gallo Tower. It only appears as a normal enemy. Killing a total of 3,000 Dragon Shrimps, including Flame Dragon Shrimps, Serpentine Dragon Shrimps and Serpentine Flame Dragon Shrimps, is the requirement for unlocking O'Sole Meeo.", "Sprite-Dragon_Shrimp.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxHealth, 4), new Stat(Stat.NomStat.XpGiven, 2), new Stat(Stat.NomStat.Might, 3), new Stat(Stat.NomStat.MoveSpeed, 200), new Stat(Stat.NomStat.KnockbackReceive, 1))),
                           new Ennemie("Flame Dragon Shrimp", "Flame Dragon Shrimp is an enemy that appears in Gallo Tower. It only appears as a normal enemy. Killing a total of 3,000 Dragon Shrimps, including Flame Dragon Shrimps, Serpentine Dragon Shrimps and Serpentine Flame Dragon Shrimps, is the requirement for unlocking O'Sole Meeo.", "Sprite-Flame_Dragon_Shrimp.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxHealth, 20), new Stat(Stat.NomStat.XpGiven, 2), new Stat(Stat.NomStat.Might, 8), new Stat(Stat.NomStat.MoveSpeed, 200), new Stat(Stat.NomStat.KnockbackReceive, 1))),
                           new Ennemie("Red Shade", "Red Shade is an enemy that appears in Inlaid Library. It only appears as a part of the map event, Shade Bomb. It chases the player and upon getting close enough it triggers its self-destruct, exploding 2 seconds later for 50 damage. It does not collide with other enemies.", "Sprite-Red_Shade.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxHealth, 11), new Stat(Stat.NomStat.XpGiven, 2), new Stat(Stat.NomStat.Might, 3), new Stat(Stat.NomStat.MoveSpeed, 330), new Stat(Stat.NomStat.KnockbackReceive, 1))),
                           new Ennemie("Poltergeist", "Poltergeist is an enemy that appears in Gallo Tower. It only appears in the map event, Poltergeist Roulette, which can be triggered by stepping on a trap. Poltergeist's health is based on the player's level. If the player gets close enough, it triggers its self-destruct, exploding 2 seconds later for 50 damage. It has no collision and does not take knockback.", "Sprite-Poltergeist.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxHealth, 1), new Stat(Stat.NomStat.XpGiven, 2), new Stat(Stat.NomStat.Might, 3), new Stat(Stat.NomStat.MoveSpeed, 0), new Stat(Stat.NomStat.KnockbackReceive, 0))),
                           new Ennemie("Nesuferit", "Nesuferit is an enemy that appears in Inlaid Library. It only appears as a boss and has a chance to drop a Treasure Chest. Killing Nesuferit is the requirement for unlocking hyper mode for Inlaid Library. It is resistant to freeze, instant kill effects and debuffs.", "Sprite-Nesuferit.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxHealth, 250), new Stat(Stat.NomStat.XpGiven, 50), new Stat(Stat.NomStat.Might, 30), new Stat(Stat.NomStat.MoveSpeed, 210), new Stat(Stat.NomStat.KnockbackReceive, 0))),
                           new Ennemie("Count", "Count is an enemy that appears in Inlaid Library. It only appears as a boss and has a chance to drop a Treasure Chest. It is resistant to freeze.", "Sprite-Count.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxHealth, 200), new Stat(Stat.NomStat.XpGiven, 50), new Stat(Stat.NomStat.Might, 30), new Stat(Stat.NomStat.MoveSpeed, 160), new Stat(Stat.NomStat.KnockbackReceive, 0))),
                           new Ennemie("Giant Skull", "Giant Skull is an enemy that appears in Gallo Tower and The Bone Zone. It only appears as a boss and has a chance to drop a Treasure Chest.", "Sprite-Giant_Skull.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxHealth, 50), new Stat(Stat.NomStat.XpGiven, 30), new Stat(Stat.NomStat.Might, 10), new Stat(Stat.NomStat.MoveSpeed, 140), new Stat(Stat.NomStat.KnockbackReceive, 1))),
                           new Ennemie("Mummy", "Mummy is an enemy that appears in Inlaid Library. It only appears as a normal enemy.", "Sprite-Mummy.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxHealth, 15), new Stat(Stat.NomStat.XpGiven, 2), new Stat(Stat.NomStat.Might, 3), new Stat(Stat.NomStat.MoveSpeed, 140), new Stat(Stat.NomStat.KnockbackReceive, 1))),
                           new Ennemie("Medusa Head", "Medusa Head is an enemy that appears in Inlaid Library. It appears as a normal enemy as well as a part of Medusa Swarm and Medusa Wall map events. Medusa Head's moves horizontally accross the screen in a wavy pattern, instead of homing to the player. The unit has a fast variant, which has higher movespeed, and and aggro variant, which has normal movespeed, but does not have the fixed movement restriction, and chases the player like most other enemies.", "Sprite-Medusa_Head.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxHealth, 25), new Stat(Stat.NomStat.XpGiven, 2), new Stat(Stat.NomStat.Might, 1), new Stat(Stat.NomStat.MoveSpeed, 240), new Stat(Stat.NomStat.KnockbackReceive, 1))),
                           new Ennemie("Harpy", "Harpy is an enemy that appears in Gallo Tower. It only appears as a normal enemy.", "Sprite-Harpy.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxHealth, 25), new Stat(Stat.NomStat.XpGiven, 2), new Stat(Stat.NomStat.Might, 1), new Stat(Stat.NomStat.MoveSpeed, 240), new Stat(Stat.NomStat.KnockbackReceive, 1))),
                           new Ennemie("Small Ectoplasm", "Small Ectoplasm is an enemy that appears in Inlaid Library. It only appears as a normal enemy.", "Sprite-Small_Ectoplasm.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxHealth, 1), new Stat(Stat.NomStat.XpGiven, 1), new Stat(Stat.NomStat.Might, 2), new Stat(Stat.NomStat.MoveSpeed, 160), new Stat(Stat.NomStat.KnockbackReceive, 1))),
                           new Ennemie("Ectoplasm", "Ectoplasm is an enemy that appears in Inlaid Library and Dairy Plant. In Inlaid Library it only appears as a normal enemy, and in Dairy Plant it appears as an event enemy from a trap.", "Sprite-Ectoplasm.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxHealth, 15), new Stat(Stat.NomStat.XpGiven, 1), new Stat(Stat.NomStat.Might, 4), new Stat(Stat.NomStat.MoveSpeed, 160), new Stat(Stat.NomStat.KnockbackReceive, 1))),
                           new Ennemie("Imp", "Imp is an enemy that appears in Gallo Tower. It appears as a normal enemy and in the map event, Imp Swarm, triggered by stepping on a trap.", "Sprite-Imp.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxHealth, 13), new Stat(Stat.NomStat.XpGiven, 1), new Stat(Stat.NomStat.Might, 4), new Stat(Stat.NomStat.MoveSpeed, 160), new Stat(Stat.NomStat.KnockbackReceive, 1))),
                           new Ennemie("Lesser Dullahan", "Lesser Dullahan is an enemy that appears in Gallo Tower. It only appears as a normal enemy.", "Sprite-Lesser_Dullahan.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxHealth, 35), new Stat(Stat.NomStat.XpGiven, 1), new Stat(Stat.NomStat.Might, 8), new Stat(Stat.NomStat.MoveSpeed, 100), new Stat(Stat.NomStat.KnockbackReceive, 1)))
                           );

            AjoutCollection(lesArmesPassives,
                            new ArmePassive("Hollow Heart", "Hollow Heart is a passive item in Vampire Survivors. It is unlocked by surviving 1 minute as any character. Hollow Heart multiplies Max Health by 1.2 per level. Hollow Heart is required for the Evolution of Whip, Bloody Tear. Hollow Heart can be found as a stage item in Mad Forest and Moongolow.", "Sprite-Hollow_Heart.png", ConstructionParticularite(new Stat(Stat.NomStat.Rarity, 90), new Stat(Stat.NomStat.MaxLevel, 5)), new List<HashSet<Stat>>()),
                            new ArmePassive("Empty Tome", "Empty Tome is a passive item in Vampire Survivors. It is unlocked by holding 6 different weapons at once. Empty Tome reduces the Cooldown of weapons by 8 % per level. Empty Tome is required for the Evolution of Magic Wand, Holy Wand. Empty Tome can be found as a stage item in Inlaid Library and Moongolow.", "Sprite-Empty_Tome.png", ConstructionParticularite(new Stat(Stat.NomStat.Rarity, 50), new Stat(Stat.NomStat.MaxLevel, 5)), new List<HashSet<Stat>>()),
                            new ArmePassive("Bracer", "Bracer is a passive item in Vampire Survivors. It is unlocked by getting King Bible to Level 4. Bracer increases Projectile Speed by 10 % per level. Bracer is required for the Evolution of Knife, Thousand Edge. Bracer can be found as a stage item in Gallo Tower and Moongolow.", "Sprite-Bracer.png", ConstructionParticularite(new Stat(Stat.NomStat.Rarity, 100), new Stat(Stat.NomStat.MaxLevel, 5)), new List<HashSet<Stat>>()),
                            new ArmePassive("Duplicator", "Duplicator is a passive item in Vampire Survivors. It is unlocked by getting the Magic Wand to Level 7. Duplicator increases Amount by + 1 per level. Duplicator is required for the Evolution of Lightning Ring, Thunder Loop. Duplicator can be found as a stage item in Cappella Magna and Moongolow.", "Sprite-Duplicator.png", ConstructionParticularite(new Stat(Stat.NomStat.Rarity, 50), new Stat(Stat.NomStat.MaxLevel, 2)), new List<HashSet<Stat>>()),
                            new ArmePassive("Crown", "Crown is a passive item in Vampire Survivors. It is unlocked by reaching Level 10 as any character. Crown boosts experience gain by + 8 % per level. Crown is required for the Evolution of Pentagram, Gorgeous Moon. Crown can be found as a stage item in Cappella Magna and Moongolow.", "Sprite-Crown.png", ConstructionParticularite(new Stat(Stat.NomStat.Rarity, 70), new Stat(Stat.NomStat.MaxLevel, 5)), new List<HashSet<Stat>>()),
                            new ArmePassive("Gold Ring", "Gold Ring is a passive item in Vampire Survivors. It is unlocked after obtaining the Yellow Sign. It cannot be found via level ups, and must be found as a stage item. Gold Ring increases Curse by 5 % per level. Gold Ring is required for the Evolution of the Clock Lancet, Infinite Corridor. Gold Ring can be found as a stage item in every stage.Generally, it will always spawn south of the starting area, except in Inlaid Library and Cappella Magna, where it spawns to the east instead.It will always be guarded by a Masked Guardian.", "Sprite-Gold_Ring.png", ConstructionParticularite(new Stat(Stat.NomStat.Rarity, 10), new Stat(Stat.NomStat.MaxLevel, 9)), new List<HashSet<Stat>>()),
                            new ArmePassive("Metaglio Left", "Metaglio Left is a passive item in Vampire Survivors. It is unlocked after obtaining the Yellow Sign. It cannot be found via level ups, and must be found as a stage item. Metaglio Left increases Recovery by 0.1 and multiplies Max Health by 1.05 per level. Metaglio Left is required for the Evolution of the Laurel, the Crimson Shroud. Metaglio Left can be found as a stage item in every stage.Generally, it will always spawn west of the starting area, except in Gallo Tower, where it spawns to the north instead.It will always be guarded by a Masked Guardian.", "Sprite-Metaglio_Left.png", ConstructionParticularite(new Stat(Stat.NomStat.Rarity, 10), new Stat(Stat.NomStat.MaxLevel, 9)), new List<HashSet<Stat>>()),
                            new ArmePassive("Candelabrador", "Candelabrador is a passive item in Vampire Survivors. It is unlocked by getting Santa Water to Level 4. Candelabrador increases Area by 10 % per level. Candelabrador is required for the Evolution of Axe, Death Spiral. Candelabrador can be found as a stage item in Dairy Plant and Moongolow.", "Sprite-Candelabrador.png", ConstructionParticularite(new Stat(Stat.NomStat.Rarity, 100), new Stat(Stat.NomStat.MaxLevel, 5)), new List<HashSet<Stat>>()),
                            new ArmePassive("Clover", "Clover is a passive item in Vampire Survivors. It is unlocked by finding a Little Clover from a light source. Clover increases Luck by 10 % per level. Clover is required for the Evolution of Cross, Heaven Sword. Clover can be found as a stage item in Mad Forest and Moongolow.", "Sprite-Clover.png", ConstructionParticularite(new Stat(Stat.NomStat.Rarity, 100), new Stat(Stat.NomStat.MaxLevel, 5)), new List<HashSet<Stat>>()),
                            new ArmePassive("Spellbinder", "Spellbinder is a passive item in Vampire Survivors. It is unlocked by getting the Runetracer to Level 7. Spellbinder increases Duration by 10 % per level. Spellbinder is required for the Evolution of King Bible, Unholy Vespers. Spellbinder can be found as a stage item in Gallo Tower and Moongolow.", "Sprite-Spellbinder.png", ConstructionParticularite(new Stat(Stat.NomStat.Rarity, 100), new Stat(Stat.NomStat.MaxLevel, 5)), new List<HashSet<Stat>>()),
                            new ArmePassive("Spinach", "Spinach is a passive item in Vampire Survivors. It is unlocked by default. Spinach increases Might by 10 % per level. Spinach is required for the Evolution of Fire Wand, Hellfire. Spinach can be found as a stage item in Mad Forest and Moongolow.", "Sprite-Spinach.png", ConstructionParticularite(new Stat(Stat.NomStat.Rarity, 100), new Stat(Stat.NomStat.MaxLevel, 5)), new List<HashSet<Stat>>()),
                            new ArmePassive("Pummarola", "Pummarola is a passive item in Vampire Survivors. It is unlocked by surviving 5 minutes as Gennaro Belpaese. Pummarola increases Recovery by 0.2 per level. Pummarola is required for the Evolution of Garlic, Soul Eater. Pummarola can be found as a stage item in Mad Forest and Moongolow.", "Sprite-Pummarola.png", ConstructionParticularite(new Stat(Stat.NomStat.Rarity, 90), new Stat(Stat.NomStat.MaxLevel, 5)), new List<HashSet<Stat>>()),
                            new ArmePassive("Attractorb", "Attractorb is a passive item in Vampire Survivors. It is unlocked upon finding a Vacuum dropped by a light source. Attractorb gives multiplicative bonuses of varying size to the player's Magnet stat. Attractorb is required for the Evolution of Santa Water, La Borra. Attractorb can be found as a stage item in Dairy Plant and Moongolow.", "Sprite-Atract_Orb.png", ConstructionParticularite(new Stat(Stat.NomStat.Rarity, 100), new Stat(Stat.NomStat.MaxLevel, 5)), new List<HashSet<Stat>>()),
                            new ArmePassive("Armor", "Armor is a passive item in Vampire Survivors. It is unlocked by default. Armor increases Armor by 1 per level, reducing all damage dealt to the player by 1.It cannot reduce damage to 0.Armor also increase retaliatory damage by 10 % additively and it is an additional multiplier on top of Might. Armor is required for the Evolution of Runetracer, NO FUTURE. Armor can be found as a stage item in Dairy Plant and Moongolow.", "Sprite-Armor.png", ConstructionParticularite(new Stat(Stat.NomStat.Rarity, 100), new Stat(Stat.NomStat.MaxLevel, 5)), new List<HashSet<Stat>>())
                            );

            AjoutCollection(lesArmesActives,
                            new ArmeActive("Whip", "Whip is a weapon in Vampire Survivors. It is the starting weapon of Antonio Belpaese. It is unlocked by default, and can be offered to the player from the start. Whip can be evolved into Bloody Tear with Hollow Heart.", "Sprite-Whip.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxLevel, 8), new Stat(Stat.NomStat.Might, 10), new Stat(Stat.NomStat.Area, 1), new Stat(Stat.NomStat.Speed, 1), new Stat(Stat.NomStat.Amount, 1), new Stat(Stat.NomStat.Knockback, 1), new Stat(Stat.NomStat.Luck, 20), new Stat(Stat.NomStat.CritMultiplier, 2), new Stat(Stat.NomStat.Rarity, 100)), new List<HashSet<Stat>>()),
                            new ArmeActive("Magic Wand", "Magic Wand is a weapon in Vampire Survivors. It is the starting weapon of Imelda Belpaese. It is unlocked by default, and can be offered to the player from the start. Magic Wand can be evolved into Holy Wand with Empty Tome.", "Sprite-Magic_Wand.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxLevel, 8), new Stat(Stat.NomStat.Might, 10), new Stat(Stat.NomStat.Area, 1), new Stat(Stat.NomStat.Speed, 1), new Stat(Stat.NomStat.Amount, 1), new Stat(Stat.NomStat.Knockback, 1),new Stat(Stat.NomStat.Cooldown, 1), new Stat(Stat.NomStat.Rarity, 100)), new List<HashSet<Stat>>()),
                            new ArmeActive("Knife", "Knife is a weapon in Vampire Survivors. It is the starting weapon of Gennaro Belpaese. It is unlocked by default, and can be offered to the player from the start Knife can be evolved into the Thousand Edge with Bracer.", "Sprite-Knife.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxLevel, 8), new Stat(Stat.NomStat.Might, 7), new Stat(Stat.NomStat.Area, 1), new Stat(Stat.NomStat.Speed, 1), new Stat(Stat.NomStat.Amount, 1), new Stat(Stat.NomStat.Knockback, 1),new Stat(Stat.NomStat.Cooldown, 1), new Stat(Stat.NomStat.Rarity, 100)), new List<HashSet<Stat>>()),
                            new ArmeActive("Axe", "Axe is a weapon in Vampire Survivors. It is the starting weapon of Lama Ladonna. It is unlocked by default, and can be offered to the player from the start Axe can be evolved into Death Spiral with Candelabrador.", "Sprite-Axe.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxLevel, 8), new Stat(Stat.NomStat.Might, 20), new Stat(Stat.NomStat.Area, 1), new Stat(Stat.NomStat.Speed, 1), new Stat(Stat.NomStat.Amount, 1), new Stat(Stat.NomStat.Knockback, 1),new Stat(Stat.NomStat.Cooldown, 4), new Stat(Stat.NomStat.Rarity, 100)), new List<HashSet<Stat>>()),
                            new ArmeActive("Cross", "Cross is a weapon in Vampire Survivors. It is the starting weapon of Krochi Freetto. It is unlocked by finding a Rosary Cross can be evolved into the Heaven Sword with Clover.", "Sprite-Cross.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxLevel, 8), new Stat(Stat.NomStat.Might, 5), new Stat(Stat.NomStat.Area, 1), new Stat(Stat.NomStat.Speed, 1), new Stat(Stat.NomStat.Amount, 1), new Stat(Stat.NomStat.Knockback, 1),new Stat(Stat.NomStat.Cooldown, 2), new Stat(Stat.NomStat.Rarity, 80)), new List<HashSet<Stat>>()),
                            new ArmeActive("King Bible", "King Bible is a weapon in Vampire Survivors. It is the starting weapon of Dommario. It is unlocked by default, and can be offered to the player from the start It can be evolved into Unholy Vespers with Spellbinder.", "Sprite-King_Bible.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxLevel, 8), new Stat(Stat.NomStat.Might, 10), new Stat(Stat.NomStat.Area, 1), new Stat(Stat.NomStat.Speed, 1), new Stat(Stat.NomStat.Amount, 1), new Stat(Stat.NomStat.Knockback, 1),new Stat(Stat.NomStat.Duration, 3), new Stat(Stat.NomStat.Cooldown, 3), new Stat(Stat.NomStat.Rarity, 80)), new List<HashSet<Stat>>()),
                            new ArmeActive("Fire Wand", "Fire Wand is a weapon in Vampire Survivors. It is the starting weapon for Arca Ladonna. It is unlocked for all characters after destroying 20 Torches Fire Wand may be evolved into Hellfire with Spinach.", "Sprite-Fire_Wand.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxLevel, 8), new Stat(Stat.NomStat.Might, 20), new Stat(Stat.NomStat.Area, 1), new Stat(Stat.NomStat.Speed, 1), new Stat(Stat.NomStat.Amount, 3), new Stat(Stat.NomStat.Knockback, 1),new Stat(Stat.NomStat.Cooldown, 3), new Stat(Stat.NomStat.Rarity, 80)), new List<HashSet<Stat>>()),
                            new ArmeActive("Garlic", "Garlic is a weapon in Vampire Survivors. It is the starting weapon of Poe Ratcho. It is unlocked by consuming five Floor Chicken. Garlic can be evolved into Soul Eater with Pummarola.", "Sprite-Garlic.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxLevel, 8), new Stat(Stat.NomStat.Might, 5), new Stat(Stat.NomStat.Area, 1), new Stat(Stat.NomStat.Speed, 1), new Stat(Stat.NomStat.Amount, 1),new Stat(Stat.NomStat.Cooldown, 1), new Stat(Stat.NomStat.Rarity, 70)), new List<HashSet<Stat>>()),
                            new ArmeActive("Santa Water", "Santa Water is a weapon in Vampire Survivors. It is the starting weapon of Suor Clerici. It is unlocked by default, and can be offered to the player from the start. Santa Water can be Evolved into La Borra with Attractorb.", "Sprite-Santa_Water.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxLevel, 8), new Stat(Stat.NomStat.Might, 10), new Stat(Stat.NomStat.Area, 1), new Stat(Stat.NomStat.Speed, 1), new Stat(Stat.NomStat.Amount, 1), new Stat(Stat.NomStat.Knockback, 1),new Stat(Stat.NomStat.Duration, 2), new Stat(Stat.NomStat.Cooldown, 5), new Stat(Stat.NomStat.Rarity, 100)), new List<HashSet<Stat>>()),
                            new ArmeActive("Runetracer", "Runetracer is a weapon in Vampire Survivors. It is the starting weapon of Pasqualina Belpaese. It is unlocked by surviving 5 minutes as Pasqualina. It can be evolved into NO FUTURE with Armor.", "Sprite-Runetracer.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxLevel, 8), new Stat(Stat.NomStat.Might, 10), new Stat(Stat.NomStat.Area, 1), new Stat(Stat.NomStat.Speed, 1), new Stat(Stat.NomStat.Amount, 3), new Stat(Stat.NomStat.Knockback, 1),new Stat(Stat.NomStat.Duration, 2), new Stat(Stat.NomStat.Cooldown, 3), new Stat(Stat.NomStat.Rarity, 80)), new List<HashSet<Stat>>()),
                            new ArmeActive("Lightning Ring", "Lightning Ring is a weapon in Vampire Survivors. It is the starting weapon of Porta Ladonna. It is unlocked by defeating 5000 enemies. Lightning Ring can be evolved into Thunder Loop with Duplicator.", "Sprite-Lightning_Ring.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxLevel, 8), new Stat(Stat.NomStat.Might, 15), new Stat(Stat.NomStat.Area, 1), new Stat(Stat.NomStat.Speed, 1), new Stat(Stat.NomStat.Amount, 2), new Stat(Stat.NomStat.Knockback, 1),new Stat(Stat.NomStat.Cooldown, 5), new Stat(Stat.NomStat.Rarity, 80)), new List<HashSet<Stat>>()),
                            new ArmeActive("Pentagram", "Pentagram is a weapon in Vampire Survivors. It is the starting weapon of Christine Davain. It is unlocked by surviving for 20 minutes as any character. Pentagram can be evolved into Gorgeous Moon with Crown.", "Sprite-Pentagram.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxLevel, 8), new Stat(Stat.NomStat.Area, 1), new Stat(Stat.NomStat.Speed, 1), new Stat(Stat.NomStat.Amount, 1), new Stat(Stat.NomStat.Knockback, -2),new Stat(Stat.NomStat.Cooldown, 90),new Stat(Stat.NomStat.Luck, 10), new Stat(Stat.NomStat.Rarity, 80)), new List<HashSet<Stat>>()),
                            new ArmeActive("Clock Lancet", "Clock Lancet is a supporting weapon in Vampire Survivors. It is the starting weapon of Iguana Gallo Valletto. It is unlocked by collecting a Orologion for the first time. Clock Lancet can be evolved into Infinite Corridor with Gold Ring at max level.", "Sprite-Clock_Lancet.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxLevel, 7), new Stat(Stat.NomStat.Area, 1), new Stat(Stat.NomStat.Speed, 1), new Stat(Stat.NomStat.Amount, 1),new Stat(Stat.NomStat.Duration, 2), new Stat(Stat.NomStat.Cooldown, 2), new Stat(Stat.NomStat.Rarity, 70)), new List<HashSet<Stat>>()),
                            new ArmeActive("Laurel", "Laurel is a supporting weapon in Vampire Survivors. It is the starting weapon of Divano Thelma. It is unlocked by default, and can be offered to the player from the start. Laurel can be evolved into Crimson Shroud with Metaglio Left at max level.", "Sprite-Laurel.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxLevel, 7),new Stat(Stat.NomStat.Might, 10), new Stat(Stat.NomStat.Area, 1), new Stat(Stat.NomStat.Speed, 1), new Stat(Stat.NomStat.Amount, 1), new Stat(Stat.NomStat.Cooldown, 10),new Stat(Stat.NomStat.Knockback, 1), new Stat(Stat.NomStat.Rarity, 60)), new List<HashSet<Stat>>())
                            );

            AjoutCollection(lesAmeliorations,
                            new Amelioration("Bloody Tear", "Bloody Tear is a weapon in Vampire Survivors. It is the evolution of Whip, requiring Hollow Heart.", "Sprite-Bloody_Tear.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxLevel, 1), new Stat(Stat.NomStat.Rarity, 1), new Stat(Stat.NomStat.Might, 40), new Stat(Stat.NomStat.Area, 1), new Stat(Stat.NomStat.Speed, 1), new Stat(Stat.NomStat.Amount, 2), new Stat(Stat.NomStat.Cooldown, 1), new Stat(Stat.NomStat.Knockback, 1), new Stat(Stat.NomStat.Luck, 10), new Stat(Stat.NomStat.CritMultiplier, 2)), "Whip", "Hollow Heart", new List<HashSet<Stat>>()),
                            new Amelioration("Holy Wand", "Holy Wand is a weapon in Vampire Survivors. It is the evolution of Magic Wand, requiring Empty Tome. It is also the starting weapon of Leda.", "Sprite-Holy_Wand.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxLevel, 1), new Stat(Stat.NomStat.Rarity, 1), new Stat(Stat.NomStat.Might, 30), new Stat(Stat.NomStat.Area, 1), new Stat(Stat.NomStat.Speed, 2), new Stat(Stat.NomStat.Amount, 4), new Stat(Stat.NomStat.Cooldown, 1), new Stat(Stat.NomStat.Knockback, 1)), "Magic Wand", "Empty Tome", new List<HashSet<Stat>>()),
                            new Amelioration("Thousand Edge", "Thousand Edge is a weapon in Vampire Survivors. It is the evolution of Knife, requiring Bracer. It is also the starting weapon of Boon Marrabbio.", "Sprite-Thousand_Edge.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxLevel, 1), new Stat(Stat.NomStat.Rarity, 1), new Stat(Stat.NomStat.Might, 17), new Stat(Stat.NomStat.Area, 1), new Stat(Stat.NomStat.Speed, 2), new Stat(Stat.NomStat.Amount, 6), new Stat(Stat.NomStat.Cooldown, 1), new Stat(Stat.NomStat.Knockback, 1), new Stat(Stat.NomStat.Luck, 50), new Stat(Stat.NomStat.CritMultiplier, 3)), "Knife", "Bracer", new List<HashSet<Stat>>()),
                            new Amelioration("Death Spiral", "Death Spiral is a weapon in Vampire Survivors. It is the evolution of Axe, requiring the Candelabrador. It is also the starting weapon of Mask of the Red Death.", "Sprite-Death_Spiral.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxLevel, 1), new Stat(Stat.NomStat.Rarity, 1), new Stat(Stat.NomStat.Might, 60), new Stat(Stat.NomStat.Area, 1), new Stat(Stat.NomStat.Speed, 1), new Stat(Stat.NomStat.Amount, 9), new Stat(Stat.NomStat.Cooldown, 4), new Stat(Stat.NomStat.Knockback, 1), new Stat(Stat.NomStat.Luck, 30), new Stat(Stat.NomStat.CritMultiplier, 2)), "Axe", "Candelabrador", new List<HashSet<Stat>>()),
                            new Amelioration("Heaven Sword", "Heaven Sword is a weapon in Vampire Survivors. It is the evolution of Cross, requiring Clover.", "Sprite-Heaven_Sword.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxLevel, 1), new Stat(Stat.NomStat.Rarity, 1), new Stat(Stat.NomStat.Might, 77), new Stat(Stat.NomStat.Area, 1), new Stat(Stat.NomStat.Speed, 2), new Stat(Stat.NomStat.Amount, 1), new Stat(Stat.NomStat.Cooldown, 3), new Stat(Stat.NomStat.Knockback, 6), new Stat(Stat.NomStat.Luck, 10), new Stat(Stat.NomStat.CritMultiplier, 3)), "Cross", "Clover", new List<HashSet<Stat>>()),
                            new Amelioration("Unholy Vespers", "Unholy Vespers are a weapon in Vampire Survivors. It is the evolution of King Bible, requiring Spellbinder.", "Sprite-Unholy_Vespers.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxLevel, 1), new Stat(Stat.NomStat.Rarity, 1), new Stat(Stat.NomStat.Might, 30), new Stat(Stat.NomStat.Area, 2), new Stat(Stat.NomStat.Speed, 2), new Stat(Stat.NomStat.Amount, 4), new Stat(Stat.NomStat.Duration, 3), new Stat(Stat.NomStat.Cooldown, 3), new Stat(Stat.NomStat.Knockback, 4)), "King Bible", "Spellbinder", new List<HashSet<Stat>>()),
                            new Amelioration("Hellfire", "Hellfire is a weapon in Vampire Survivors. It is the evolution of Fire Wand, requiring Spinach.", "Sprite-Hellfire.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxLevel, 1), new Stat(Stat.NomStat.Rarity, 1), new Stat(Stat.NomStat.Might, 100), new Stat(Stat.NomStat.Area, 1), new Stat(Stat.NomStat.Speed, 1), new Stat(Stat.NomStat.Amount, 2), new Stat(Stat.NomStat.Cooldown, 3), new Stat(Stat.NomStat.Knockback, 1)), "Fire Wand", "Spinach", new List<HashSet<Stat>>()),
                            new Amelioration("Soul Eater", "Soul Eater is a weapon in Vampire Survivors. It is the evolution of Garlic, requiring Pummarola.", "Sprite-Soul_Eater.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxLevel, 1), new Stat(Stat.NomStat.Rarity, 1), new Stat(Stat.NomStat.Might, 20), new Stat(Stat.NomStat.Area, 3), new Stat(Stat.NomStat.Speed, 1), new Stat(Stat.NomStat.Amount, 1), new Stat(Stat.NomStat.Cooldown, 1)), "Garlic", "Pummarola", new List<HashSet<Stat>>()),
                            new Amelioration("La Borra", "La Borra is a weapon in Vampire Survivors. It is the evolution of Santa Water, requiring Attractorb.", "Sprite-La_Borra.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxLevel, 1), new Stat(Stat.NomStat.Rarity, 1), new Stat(Stat.NomStat.Might, 40), new Stat(Stat.NomStat.Area, 2), new Stat(Stat.NomStat.Speed, 1), new Stat(Stat.NomStat.Amount, 4), new Stat(Stat.NomStat.Duration, 4), new Stat(Stat.NomStat.Cooldown, 4)), "Santa Water", "Attractorb", new List<HashSet<Stat>>()),
                            new Amelioration("NO FUTURE", "NO FUTURE is a weapon in Vampire Survivors. It is the evolution of Runetracer, requiring Armor.", "Sprite-NO_FUTURE.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxLevel, 1), new Stat(Stat.NomStat.Rarity, 1), new Stat(Stat.NomStat.Might, 30), new Stat(Stat.NomStat.Area, 1), new Stat(Stat.NomStat.Speed, 3), new Stat(Stat.NomStat.Amount, 1), new Stat(Stat.NomStat.Duration, 3), new Stat(Stat.NomStat.Cooldown, 1), new Stat(Stat.NomStat.Knockback, 1)), "Runetracer", "Armor", new List<HashSet<Stat>>()),
                            new Amelioration("Thunder Loop", "Thunder Loop is a weapon in Vampire Survivors. It is the evolution of Lightning Ring, requiring Duplicator.", "Sprite-Thunder_Loop.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxLevel, 1), new Stat(Stat.NomStat.Rarity, 1), new Stat(Stat.NomStat.Might, 65), new Stat(Stat.NomStat.Area, 4), new Stat(Stat.NomStat.Speed, 1), new Stat(Stat.NomStat.Amount, 6), new Stat(Stat.NomStat.Cooldown, 5), new Stat(Stat.NomStat.Knockback, 1)), "Lightning Ring", "Duplicator", new List<HashSet<Stat>>()),
                            new Amelioration("Gorgeous Moon", "Gorgeous Moon is a weapon in Vampire Survivors. It is the evolution of Pentagram, requiring Crown.", "Sprite-Gorgeous_Moon.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxLevel, 1), new Stat(Stat.NomStat.Rarity, 1), new Stat(Stat.NomStat.Area, 1), new Stat(Stat.NomStat.Speed, 1), new Stat(Stat.NomStat.Amount, 1), new Stat(Stat.NomStat.Cooldown, 60), new Stat(Stat.NomStat.Knockback, 1), new Stat(Stat.NomStat.Luck, 100)), "Pentagram", "Crown", new List<HashSet<Stat>>()),
                            new Amelioration("Infinite Corridor", "Infinite Corridor is a weapon in Vampire Survivors. It is the evolution of Clock Lancet, requiring Gold Ring at max level.", "Sprite-Infinite_Corridor.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxLevel, 1), new Stat(Stat.NomStat.Rarity, 1), new Stat(Stat.NomStat.Area, 1), new Stat(Stat.NomStat.Speed, 1), new Stat(Stat.NomStat.Amount, 1), new Stat(Stat.NomStat.Duration, 6), new Stat(Stat.NomStat.Cooldown, 1)), "Clock Lancet", "Gold Ring", new List<HashSet<Stat>>()),
                            new Amelioration("Crimson Shroud", "Crimson Shroud is a weapon in Vampire Survivors. It is the evolution of Laurel, requiring Metaglio Left fully leveled to evolve.", "Sprite-Crimson_Shroud.png", ConstructionParticularite(new Stat(Stat.NomStat.MaxLevel, 1), new Stat(Stat.NomStat.Rarity, 1),new Stat(Stat.NomStat.Might, 0), new Stat(Stat.NomStat.Area, 2), new Stat(Stat.NomStat.Speed, 1), new Stat(Stat.NomStat.Amount, 1), new Stat(Stat.NomStat.Cooldown, 8), new Stat(Stat.NomStat.Knockback, 20)), "Laurel", "Metaglio Left", new List<HashSet<Stat>>())
                            );

            AjoutCollection(lesPersonnages,
                            new Personnage("Antonio Belpaese",
                                            "Antonio Belpaese is one of the playable characters in Vampire Survivors. He is the character that every player begins with and he is the only free character in the game. His starting weapon is the Whip. He gains +10% Might every 10 levels until level 50. The maximum Might gained this way is +50%.",
                                            "antonio.png",
                                            ConstructionParticularite(new Stat(Stat.NomStat.MaxHealth, 20),
                                                                        new Stat(Stat.NomStat.Armor, 1),
                                                                        new Stat(Stat.NomStat.Might, 1)),
                                            "Whip"),
                            new Personnage("Imelda Belpaese",
                                            "Imelda Belpaese is one of the playable characters in Vampire Survivors. Her starting weapon is Magic Wand. Imelda gains +10% Growth every 5 levels until level 15. The maximum Growth gained this way is +30%. ",
                                            "imelda.png",
                                            ConstructionParticularite(),
                                            "Magic Wand"),
                            new Personnage("Pasqualina Belpaese",
                                            "Pasqualina Belpaese is one of the playable characters in Vampire Survivors. Her starting weapon is Runetracer. Pasqualina she gains +10% Speed every 5 levels until level 15. The maximum Speed gained this way is +30%, or +40% with the starting bonus included. ",
                                            "pasqualina.png",
                                            ConstructionParticularite(new Stat(Stat.NomStat.Speed, 10)),
                                            "Runetracer"),
                            new Personnage("Gennaro Belpaese",
                                            "Gennaro Belpaese is one of the playable characters in Vampire Survivors. His starting weapon is Knife.",
                                            "gennaro.png",
                                            ConstructionParticularite(new Stat(Stat.NomStat.MaxHealth, 20),
                                                                        new Stat(Stat.NomStat.Amount, 1)),
                                            "Knife"),
                            new Personnage("Arca Ladonna",
                                            "Arca Ladonna is one of the playable characters in Vampire Survivors. His starting weapon is Fire Wand. Arca gains -5% Cooldown every 10 levels until level 30. The maximum Cooldown reduction gained this way is -15%.",
                                            "arca.png",
                                            ConstructionParticularite(),
                                            "Fire Wand"),
                            new Personnage("Porta Ladonna",
                                            "Porta Ladonna is one of the playable characters in Vampire Survivors. Her starting weapon is Lightning Ring. Porta starts with -90% Cooldown bonus, which increases by 30% on every level up until negated upon reaching level 4, allowing the Lightning Ring to quickly kill enemies for experience. ",
                                            "antonio.png",
                                            ConstructionParticularite(new Stat(Stat.NomStat.MaxHealth, 20),
                                                                      new Stat(Stat.NomStat.Armor, 1),
                                                                      new Stat(Stat.NomStat.Might, 1)),
                                            "Lightning Ring"));
            AjoutCollection(lesCartes,
                new Carte("Carte 1","","", new List<string>() { "Ennemie 1" }, new List<string>() { "Arme Passive 1" }),
                new Carte("Carte 2", "", "", new List<string>() { "Ennemie 2" }, new List<string>() { "Arme Passive 2" }));

            LiensDesClasses(lesArmesPassives, lesArmesActives, lesAmeliorations, lesCartes, lesEnnemies,lesPersonnages);

            return (lesArmesPassives,lesArmesActives,lesAmeliorations, lesPersonnages, lesEnnemies, lesCartes);
        }
        private void AjoutCollection<T>(HashSet<T> list, params T[] liste) where T : Element
        {
            list.UnionWith(liste);
        }

        private HashSet<Stat> ConstructionParticularite(params Stat[] liste)
        {
            HashSet<Stat> res = new HashSet<Stat>();
            res.UnionWith(liste);
            return res;
        }
        public void LiensDesClasses(HashSet<ArmePassive> armesPassives, HashSet<ArmeActive> armesActives, HashSet<Amelioration> ameliortions, HashSet<Carte> cartes, HashSet<Ennemie> ennemies,HashSet<Personnage> persos)
        {
            foreach (Amelioration amelio in ameliortions)
            {
                foreach (ArmeActive active in armesActives)
                {
                    if (amelio.NomArmeAct == active.Nom)
                    {
                        amelio.ArmeAct = active;
                        active.ajouterAmelioration(amelio);
                    }
                }
                foreach (ArmePassive passive in armesPassives)
                {
                    if (amelio.NomArmePass == passive.Nom)
                    {
                        amelio.ArmePass = passive;
                        passive.ajouterAmelioration(amelio);
                        passive.ajouterArmeActive(amelio.ArmeAct);
                    }
                }
                foreach (ArmeActive active in armesActives)
                {
                    if (amelio.NomArmeAct == active.Nom)
                    {
                        active.ajouterArmePasssive(amelio.ArmePass);
                    }
                }
            }
            foreach (Carte carte in cartes)
            {
                carte.LesEnnemies = (from en in ennemies
                                     join nomen in carte.NomEnn on en.Nom equals nomen
                                     select en).ToList();

                carte.LesObjetsCaches = (from ap in armesPassives
                                         join objcach in carte.NomArmPass on ap.Nom equals objcach
                                         select ap).ToList();
            }
            foreach (Personnage p in persos)
            {
                p.Arme = armesActives.Where(a => a.Nom == p.NomArme).DefaultIfEmpty().First();
            }
        }

    }
}
